name: Sonar

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Sonar
    uses: getzoop/gha-workflows/.github/workflows/sonarcloud.yml@v5
    with:
      runs-on: pagzoop
    secrets:
      sonarcloud-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
