name: SAST Workflow

on:
  push:
    branches: [ main, develop, release/* ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '44 22 * * 0' #mudar horario

jobs:
  tfsec:
    name: TFSec
    uses: getzoop/gha-workflows/.github/workflows/tfsec.yml@v5
  codeql:
    name: CodeQL
    uses: getzoop/gha-workflows/.github/workflows/codeql.yml@v5
    with:
      language: liguagem_do_repo
